# Generated by Django 4.2.6 on 2023-11-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product_image_product_seller_alter_product_disc'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gg',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
