# Generated by Django 4.2.6 on 2023-10-12 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='disc',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
