# Generated by Django 4.2.6 on 2023-11-15 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_product_gg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='gg',
        ),
    ]
